services:
  billable_metrics_pg:
    image: postgres:15
    container_name: billable_metrics_pg
    restart: always
    environment:
      POSTGRES_DB: billable_metrics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - billable-metrics-network

  billable_metrics_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billable_metrics_app
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://billable_metrics_pg:5432/billable_metrics_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - billable_metrics_pg
    networks:
      - billable-metrics-network

networks:
  billable-metrics-network:
    driver: bridge
