services:
  billable_metrics_pg:
    image: postgres:15
    container_name: billable_metrics_pg
    restart: always
    environment:
      POSTGRES_DB: billable_metrics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - billable-metrics-network

  billable_metrics_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billable_metrics_app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://billable_metrics_pg:5432/billable_metrics_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      billable_metrics_pg:
        condition: service_started
    networks:
      - billable-metrics-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  billable-metrics-network:
    driver: bridge
